baseURL = 'https://gauravchandra.com/'
languageCode = 'en-us'
title = 'Gaurav Chandra'
theme = 'hugo-resume'
locale = 'en-us'
paginate = 5

[params]
  firstName = 'Gaurav'
  lastName = 'Chandra'
  address = 'San Jose, California'
  email = ''
  phone = ''
  profileImage = 'img/profile.jpg'
  description = 'Your short leadership tagline or bio goes here.'
  showQr = false
  showContact = false
  showSocializations = true
  sections = []

[params.customSections.blog]
  name = "Blog"
  url = "/blog/"

[[params.handles]]
  name = "LinkedIn"
  link = "https://www.linkedin.com/in/gaurav-chandra/"

[params.google]
[params.google.analytics]
  trackerID = ""

[outputs]
  home = ["HTML", "JSON"]

[taxonomies]
  tag = "tags"

